# Generated by Django 3.2.7 on 2021-09-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
